In [1]:
pip install --upgrade numpy pandas

Requirement already satisfied: numpy in c:\users\victus\anaconda3\lib\site-packages (2.2.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\victus\appdata\roaming\python\python311\site-packages (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\victus\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\victus\appdata\roaming\python\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\victus\appdata\roaming\python\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\victus\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: Skipping C:\Users\VICTUS\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\VICTUS\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\VICTUS\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\VICTUS\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\VICTUS\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\VICTUS\anaconda3\Lib\site-packages\numpy-1.26.4.dist-info due to invalid metadata entry 'name'

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9360\2080034654.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9360\2080034654.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9360\2080034654.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\VICTUS\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\VICTUS\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\VICTUS\AppData\Local\Temp\ipykernel_9360\2080034654.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\VICTUS\AppData\Roaming\Python\Python311\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\VICTUS\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\VICTUS\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [3]:
data = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
data.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

# Data Exploration:

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
data['SeniorCitizen'] = data['SeniorCitizen'].astype('object')
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   object
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.1+ MB

In [8]:
data.shape

(7043, 21)

==> Check for missing values

In [9]:
 data.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

==> Check for duplicate rows

In [10]:
unique_values_data= pd.DataFrame({
    'Column': data.columns,
    'Unique Values': [data[col].unique() for col in data.columns],
    'Count': [data[col].nunique() for col in data.columns]
})
unique_values_data

              Column                                      Unique Values  Count
0         customerID  [7590-VHVEG, 5575-GNVDE, 3668-QPYBK, 7795-CFOC...   7043
1             gender                                     [Female, Male]      2
2      SeniorCitizen                                             [0, 1]      2
3            Partner                                          [Yes, No]      2
4         Dependents                                          [No, Yes]      2
5             tenure  [1, 34, 2, 45, 8, 22, 10, 28, 62, 13, 16, 58, ...     73
6       PhoneService                                          [No, Yes]      2
7      MultipleLines                        [No phone service, No, Yes]      3
8    InternetService                             [DSL, Fiber optic, No]      3
9     OnlineSecurity                     [No, Yes, No internet service]      3
10      OnlineBackup                     [Yes, No, No internet service]      3
11  DeviceProtection                     [No, Yes, No internet service]      3
12       TechSupport                     [No, Yes, No internet service]      3
13       StreamingTV                     [No, Yes, No internet service]      3
14   StreamingMovies                     [No, Yes, No internet service]      3
15          Contract               [Month-to-month, One year, Two year]      3
16  PaperlessBilling                                          [Yes, No]      2
17     PaymentMethod  [Electronic check, Mailed check, Bank transfer...      4
18    MonthlyCharges  [29.85, 56.95, 53.85, 42.3, 70.7, 99.65, 89.1,...   1585
19      TotalCharges  [29.85, 1889.5, 108.15, 1840.75, 151.65, 820.5...   6530
20             Churn                                          [No, Yes]      2

In [11]:
duplicates = data.duplicated().sum()
print(f"\nNumber of Duplicate Rows: {duplicates}")

Number of Duplicate Rows: 0

In [12]:
numeric_cols = data.select_dtypes(include=['float64', 'int64']).columns

outliers = {}

for col in numeric_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    
    # Calculate the lower and upper bounds
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers[col] = data[(data[col] < lower_bound) | (data[col] > upper_bound)]
    
    print(f"Column: {col}")
    print(f"Lower Bound: {lower_bound}, Upper Bound: {upper_bound}")
    print(f"Number of outliers: {outliers[col].shape[0]}\n")

Column: tenure
Lower Bound: -60.0, Upper Bound: 124.0
Number of outliers: 0

Column: MonthlyCharges
Lower Bound: -46.02499999999999, Upper Bound: 171.375
Number of outliers: 0

Column: TotalCharges
Lower Bound: -4688.481250000001, Upper Bound: 8884.66875
Number of outliers: 0

#  Preprocessing and Feature Engineering:

In [13]:
data['SpendingPerMonth'] = data['TotalCharges'] / (data['tenure'] + 1)

In [14]:
cols = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 
                  'TechSupport', 'StreamingTV', 'StreamingMovies']

for col in cols:
    data[col] = data[col].replace('No internet service', 'No')

In [15]:
cols = ['MultipleLines']

for col in cols:
    data[col] = data[col].replace('No phone service', 'No')

In [16]:
cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn', 'gender',
        'OnlineSecurity', 'OnlineBackup', 'DeviceProtection','TechSupport', 'StreamingTV',
        'StreamingMovies','MultipleLines']
for col in cols:
    data[col] = data[col].map({'Yes': 1, 'No': 0, 'Female': 0, 'Male': 1,'True': 1 ,'False': 0})

# unique_values_data = pd.DataFrame({
#     'Column': data.columns,
#     'Unique Values': [list(data[col].unique()) for col in data.columns],
#     'Count': [data[col].nunique() for col in data.columns]
# })

In [17]:
data.to_csv("cleaned data before encoding and scalling.csv", index=False)

In [18]:
from sklearn.preprocessing import LabelEncoder

label_cols = ['InternetService', 'Contract']
encoder = LabelEncoder()
for col in label_cols:
    data[col] = encoder.fit_transform(data[col])

One-Hot Encoding

In [19]:
data = pd.get_dummies(data, columns=['PaymentMethod'], drop_first=True)

In [20]:
unique_values_data = pd.DataFrame({
    'Column': data.columns,
    'Unique Values': [list(data[col].unique()) for col in data.columns],
    'Count': [data[col].nunique() for col in data.columns]
})

unique_values_data

,Column,Unique Values,Count
0,customerID,"[7590-VHVEG, 5575-GNVDE, 3668-QPYBK, 7795-CFOC...",7043
1,gender,"[0, 1]",2
2,SeniorCitizen,"[0, 1]",2
3,Partner,"[1, 0]",2
4,Dependents,"[0, 1]",2
5,tenure,"[1, 34, 2, 45, 8, 22, 10, 28, 62, 13, 16, 58, ...",73
6,PhoneService,"[0, 1]",2
7,MultipleLines,"[0, 1]",2
8,InternetService,"[0, 1, 2]",3
9,OnlineSecurity,"[0, 1]",2
10,OnlineBackup,"[1, 0]",2
11,DeviceProtection,"[0, 1]",2
12,TechSupport,"[0, 1]",2
13,StreamingTV,"[0, 1]",2
14,StreamingMovies,"[0, 1]",2
15,Contract,"[0, 1, 2]",3
16,PaperlessBilling,"[1, 0]",2
17,MonthlyCharges,"[29.85, 56.95, 53.85, 42.3, 70.7, 99.65, 89.1,...",1585
18,TotalCharges,"[29.85, 1889.5, 108.15, 1840.75, 151.65, 820.5...",6530
19,Churn,"[0, 1]",2
20,SpendingPerMonth,"[14.925, 53.98571428571429, 36.050000000000004...",6652
21,PaymentMethod_Credit card (automatic),"[False, True]",2
22,PaymentMethod_Electronic check,"[True, False]",2
23,PaymentMethod_Mailed check,"[False, True]",2

Scaling

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data[['MonthlyCharges', 'TotalCharges', 'tenure','SpendingPerMonth']] = scaler.fit_transform(data[['MonthlyCharges', 'TotalCharges','tenure','SpendingPerMonth']])

In [23]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,SpendingPerMonth,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,0,1,0,-1.277445,0,0,0,0,...,0,0,1,-1.160323,-0.994194,0,-1.447223,False,True,False
1,5575-GNVDE,1,0,0,0,0.066327,1,0,0,1,...,0,1,0,-0.259629,-0.173740,0,-0.167059,False,False,True
2,3668-QPYBK,1,0,0,0,-1.236724,1,0,0,1,...,0,0,1,-0.362660,-0.959649,1,-0.754879,False,False,True
3,7795-CFOCW,1,0,0,0,0.514251,0,0,0,1,...,0,1,0,-0.746535,-0.195248,0,-0.624888,False,False,False
4,9237-HQITU,0,0,0,0,-1.236724,1,0,1,0,...,0,0,1,0.197365,-0.940457,1,-0.279660,False,True,False

In [24]:
data.to_csv("cleaned data after encoding and scalling.csv", index=False)

In [25]:
data.drop(columns=['customerID'], inplace=True)